### ISSUE TITLE
Error with Semantic Relatedness.py

### ISSUE THREAD

**Issue by 9thplayer** [norberte/NLP-course#1]
Is there any specific version of Scipy or numpy used? Seems there is some mistake. 
Could you please help if possible?

below is the error:

Traceback (most recent call last):
  File "SemanticRelatedness.py", line 259, in <module>
    print("Pearson correlation coefficient: ", str(pearsonr(goldenTruth, prediction)))
  File "/usr/lib/python3/dist-packages/scipy/stats/stats.py", line 3410, in pearsonr
    xmean = x.mean(dtype=dtype)
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 151, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: No loop matching the specified signature and casting was found for ufunc add

**Comment by norberte** [comment]
The issue is with scipy.stats.stats's pearsonr. Its API reference: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.pearsonr.html

I checked my current local computer's scipy version and it is 1.3.1. I can see that an update to 1.4.1 is available, and most likely this version upgrade breaks my previous code.

Try to use scipy 1.3.1 and see if the code still works, else use the latest version and modify my starter code based on the newest version's API reference descriptions

**Comment by 9thplayer** [comment]
Hi Norbert,

Thank you so much for prompt response. 
It would be great if you can list out all the dependency versions you have used ?

tensorflow
scipy
numpy
tqdm
sklearn
csv
